VERBOSE: True

MODEL:
  SESSION: 'Kligler'
  INPUT: 'input'
  TARGET: 'target'

OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: './dataset/Kligler/train'
  VAL_DIR: './dataset/Kligler/test'
  SAVE_DIR: './checkpoints/Kligler/models/base'
  ORI: False
  RESUME: './Kligler_epoch_42.pth'  # 从最佳checkpoint继续 (RMSE 9.592)
  NUM_WORKERS: 16
  VAL_BATCH_SIZE: 4
  VAL_NUM_WORKERS: 4
  PATIENCE: 30

LOSS:
  TYPE: 'CUSTOM'
  CONFIGS:
    CUSTOM:
      MSE_WEIGHT: 1.0
      SSIM_WEIGHT: 0.3
      FADE_WIDTH: 10
      MIN_ALPHA: 0.3

LOSS_SCHEDULER:
  ENABLE: true             # 开启微调阶段: true=启用调度器, false=使用固定权重

TESTING:
  WEIGHT: "./checkpoints/Kligler/models/base/Kligler_epoch_43.pth"
  SAVE_IMAGES: True
  BATCH_SIZE: 4
  NUM_WORKERS: 4

